version: "3.7"
services:
  typesense:
    image: typesense/typesense:0.25.2
    restart: unless-stopped
    ports:
      - "8108:8108"
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY=admin_dev_key
      - TYPESENSE_ENABLE_CORS=true
    volumes:
      - ./ts-data:/data
